WebApplication/Controllers/ThesesController.cs
namespace WebApplication.Controllers
{
    #region usings
    using Microsoft.AspNetCore.Mvc;
    using PagedList;
    using BusinessCore.Abstract;
    using Data.Db;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WebApplication.Models;
    using Data.Models.DTOs;
    using Data.Models;
    using System.Linq;
    using System.Dynamic;
    #endregion
    public class ThesesController : Controller
    {
        private readonly IThesisService _thesisService;
        private readonly IInstituteService _instituteService;
        private readonly IUniversityService _universityService;
        private ThesesContext db = new ThesesContext();

        public ThesesController(IThesisService thesisService , IInstituteService instituteService , IUniversityService universityService)
        {
            _thesisService = thesisService;
            _instituteService = instituteService;
            _universityService = universityService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var result = _thesisService.GetAll();
                if (result.IsSuccess)
                {
                    return View(result.Data);
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        
        [HttpPost]
        public IActionResult GetByNumber(string thesisNumber)
        {
            try
            {
                List<Thesis> theses = new List<Thesis>();
                var result = _thesisService.GetByNumber(Convert.ToInt32(thesisNumber));
                theses.Add(result.Data);
                if (result.IsSuccess)
                {
                    return View("Index",theses);
                }
                return View("Index", null);

            }
            catch (Exception ex)
            {
                return PartialView(ex.Message);
            }
        }
        [HttpGet]
        public IActionResult Filter()
        {
            var thesisModel = new ThesisModel();

            List<SelectListItem> universities;
            List<SelectListItem> institutes;
            universities = _universityService.List().Data.Select(i => new SelectListItem
            {
                Text = i.NAME.ToString(),
                Value = i.UNIVERSITYID.ToString()

            }).ToList();

            institutes = _instituteService.List().Data.Select(i => new SelectListItem
            {
                Text = i.NAME.ToString(),
                Value = i.INSTITUTEID.ToString()
            }).ToList();

            ViewBag.Universities = universities;
            ViewBag.Institutes = institutes;
            return View(thesisModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Filter(ThesisModel thesisModel)
        {
            var result = _thesisService.GetFilter(thesisModel);
            if (result.IsSuccess)
            {
                return View("Index",result.Data);
            }
            return View();
        }
        [HttpGet]
        public JsonResult GetData(int number)
        {
            try
            {
                var result = _thesisService.GetByNumber(number);
                if (result.Data != null)
                {
                    return Json(new { success = result.IsSuccess, message = result.Message , thesis = result.Data });
                }
                return Json(new { success = result.IsSuccess, message = result.Message });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

WebApplication/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <title>E-Shop Admin Paneli </title>

    <!-- Bootstrap CSS -->
    <link href="~/NiceAdmin/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/NiceAdmin/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/NiceAdmin/css/elegant-icons-style.css" rel="stylesheet" />
    <!-- full calendar css-->
    <link href="~/NiceAdmin/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="~/NiceAdmin/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="~/NiceAdmin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="~/NiceAdmin/css/owl.carousel.css" type="text/css">
    <link href="~/NiceAdmin/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/NiceAdmin/css/fullcalendar.css">
    <link href="~/NiceAdmin/css/widgets.css" rel="stylesheet">
    <link href="~/NiceAdmin/css/style.css" rel="stylesheet">
    <link href="~/NiceAdmin/css/style-responsive.css" rel="stylesheet" />
    <link href="~/NiceAdmin/css/xcharts.min.css" rel=" stylesheet">
    <link href="~/NiceAdmin/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.css">
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- =======================================================
      Theme Name: NiceAdmin
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body>
    <!-- container section start -->
    <section id="container" class="">


        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="index" class="logo">E-SHOP <span class="lite">Admin</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">
                <!--  search form start -->
                <ul class="nav top-menu">
                    <li>
                        <form class="navbar-form">
                            <input class="form-control" placeholder="Search" type="text">
                        </form>
                    </li>
                </ul>
                <!--  search form end -->
            </div>

            <div class="top-nav notification-row">
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">


                    <li id="alert_notificatoin_bar" class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                            <i class="icon-bell-l"></i>
                            <span class="badge bg-important">7</span>
                        </a>
                        <ul class="dropdown-menu extended notification">
                            <div class="notify-arrow notify-arrow-blue"></div>
                            <li>
                                <p class="blue">You have 4 new notifications</p>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-primary"><i class="icon_profile"></i></span>
                                    Friend Request
                                    <span class="small italic pull-right">5 mins</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-warning"><i class="icon_pin"></i></span>
                                    John location.
                                    <span class="small italic pull-right">50 mins</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-danger"><i class="icon_book_alt"></i></span>
                                    Project 3 Completed.
                                    <span class="small italic pull-right">1 hr</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="label label-success"><i class="icon_like"></i></span>
                                    Mick appreciated your work.
                                    <span class="small italic pull-right"> Today</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">See all notifications</a>
                            </li>
                        </ul>
                    </li>
                    <!-- alert notification end-->
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                            <span class="username">@* @Session["UserName"] *@</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            <li class="eborder-top">
                                <a href="#"><i class="icon_profile"></i> My Profile</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
                            </li>
                            <li>
                                <a href="#"><i class="icon_chat_alt"></i> Chats</a>
                            </li>
                            <li>
                                <a href="login.html"><i class="icon_key_alt"></i> Log Out</a>
                            </li>
                            <li>
                                <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                            </li>
                            <li>
                                <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                            </li>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">

                    <li>
                        <a href="/admincategory/index">

                            <span>Categories</span>
                        </a>
                    </li>
                    <li>
                        <a href="/adminproduct/index">

                            <span>Products</span>

                        </a>

                    </li>

                    <li>
                        <a href="/adminsales/index">

                            <span>Sales</span>

                        </a>

                    </li>


                    @*<li>
                    <a href="/adminuser/index">

                    <span>Users</span>

                    </a>

                    </li>*@

                    @*<li>
                    <a href="/administatistic/index">

                    <span>Statistics</span>

                    </a>

                    </li>*@
                    <li>
                        <a href="/admin/comment">

                            <span>Comments</span>

                        </a>

                    </li>
                    <li>
                        <a href="/admincustomer/index">

                            <span>Customers</span>

                        </a>

                    </li>
                    <li>
                        <a href="/adminorder/index">

                            <span>Orders</span>

                        </a>

                    </li>


                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()

            </section>

        </section>
        <!--main content end-->
    </section>
    <!-- container section start -->
    <!-- javascripts -->
    <script src="~/NiceAdmin/js/jquery.js"></script>
    <script src="~/NiceAdmin/js/jquery-ui-1.10.4.min.js"></script>
    <script src="~/NiceAdmin/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.9.2.custom.min.js"></script>
    <!-- bootstrap -->
    <script src="~/NiceAdmin/js/bootstrap.min.js"></script>
    <!-- nice scroll -->
    <script src="~/NiceAdmin/js/jquery.scrollTo.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.nicescroll.js" type="text/javascript"></script>
    <!-- charts scripts -->
    <script src="~/NiceAdmin/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/NiceAdmin/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/NiceAdmin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/NiceAdmin/js/owl.carousel.js"></script>
    <!-- jQuery full calendar -->
    <
    <script src="~/NiceAdmin/js/fullcalendar.min.js"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="~/NiceAdmin/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <!--script for this page only-->
    <script src="~/NiceAdmin/js/calendar-custom.js"></script>
    <script src="~/NiceAdmin/js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="~/NiceAdmin/js/jquery.customSelect.min.js"></script>
    <script src="~/NiceAdmin/assets/chart-master/Chart.js"></script>

    <!--custome script for all page-->
    <script src="~/NiceAdmin/js/scripts.js"></script>
    <!-- custom script for this page-->
    <script src="~/NiceAdmin/js/sparkline-chart.js"></script>
    <script src="~/NiceAdmin/js/easy-pie-chart.js"></script>
    <script src="~/NiceAdmin/js/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/NiceAdmin/js/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/NiceAdmin/js/xcharts.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.autosize.min.js"></script>
    <script src="~/NiceAdmin/js/jquery.placeholder.min.js"></script>
    <script src="~/NiceAdmin/js/gdp-data.js"></script>
    <script src="~/NiceAdmin/js/morris.min.js"></script>
    <script src="~/NiceAdmin/js/sparklines.js"></script>
    <script src="~/NiceAdmin/js/charts.js"></script>
    <script src="~/NiceAdmin/js/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script>
        //knob
        $(function () {
            $(".knob").knob({
                'draw': function () {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function () {
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

        /* ---------- Map ---------- */
        $(function () {
            $('#map').vectorMap({
                map: 'world_mill_en',
                series: {
                    regions: [{
                        values: gdpData,
                        scale: ['#000', '#000'],
                        normalizeFunction: 'polynomial'
                    }]
                },
                backgroundColor: '#eef3f7',
                onLabelShow: function (e, el, code) {
                    el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                }
            });
        });
    </script>

</body>

</html>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/theses/index">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/theses/filter">Detail Filter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/user/login">User Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/login">Admin Login</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 ml-auto" action="@Url.Action("GetByNumber", "Theses")" method="post">
                    <div class="form-group">
                        <input name="thesisNumber" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)`                                   
</body>
</html>